# Site settings
title: Samer Tufail
email: samertufail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Samer - Code.Food.Code.Food - Repeat 
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://samertufail.github.io" # the base hostname & protocol for your site
twitter_username: samertfl
github_username: samertufail 

# Build settings
markdown: kramdown
