url: http://samertufail.github.io
baseurl: /

# Site Settings
title: Samer Tufail
description: "Timeline is multipurpose, single page Jekyll theme that includes a timeline section."
keywords: "Samer Tufail, Samer"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
