# Site settings
title: Zaki Shaheen
email: zakishaheen@me.com
description: > # this means to ignore newlines until "baseurl:"
  Zaki starts here. 
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://zakishaheen.github.io" # the base hostname & protocol for your site
twitter_username: meetzaki
github_username: zakishaheen 

# Build settings
markdown: kramdown
